version: '3.8'

services:
  efiling-mock-server:
    build: .
    container_name: efiling-mock-server
    ports:
      - "5000:5000"
    networks:
      - share-proxy
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

networks:
  shared-proxy:
    external: true